-- Create a table for public profiles linked to auth.users
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  username text,
  role text default 'reporter', -- 'admin', 'developer', 'reporter'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- Projects table
create table projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  status text default 'development', -- 'development', 'release', 'stable', 'obsolete'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table projects enable row level security;
-- For simplicity, allow authenticated users to view projects
create policy "Authenticated users can view projects" on projects for select using ( auth.role() = 'authenticated' );
-- Only admins/devs should ideally edit, but for now allow authenticated insert
create policy "Authenticated users can create projects" on projects for insert with check ( auth.role() = 'authenticated' );

-- Issues table
create table issues (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) not null,
  title text not null,
  description text,
  status text default 'new', -- 'new', 'assigned', 'resolved', 'closed'
  priority text default 'normal', -- 'low', 'normal', 'high', 'immediate'
  severity text default 'minor', -- 'feature', 'minor', 'major', 'crash'
  created_by uuid references auth.users not null,
  assigned_to uuid references auth.users,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table issues enable row level security;
create policy "Authenticated users can view issues" on issues for select using ( auth.role() = 'authenticated' );
create policy "Authenticated users can create issues" on issues for insert with check ( auth.role() = 'authenticated' );
create policy "Authenticated users can update issues" on issues for update using ( auth.role() = 'authenticated' );

-- Comments/Notes table
create table notes (
  id bigint generated by default as identity primary key,
  issue_id bigint references issues(id) not null,
  user_id uuid references profiles(id) not null,
  note text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table notes enable row level security;
create policy "Authenticated users can view notes" on notes for select using ( auth.role() = 'authenticated' );
create policy "Authenticated users can create notes" on notes for insert with check ( auth.role() = 'authenticated' );

-- Trigger to handle new user signup automatically
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username)
  values (new.id, new.email, new.raw_user_meta_data->>'username');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
